pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git credentialsId: 'github-pat', url: 'https://github.com/oriax18/python-webapp.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                bat 'docker build -t python-webapp .'
            }
        }
        stage('Stop Existing Container') {
            steps {
                bat '''
                docker stop python-web-container || echo "Container not running"
                docker rm python-web-container || echo "Container not exists"
                '''
            }
        }
        stage('Run Docker Container') {
            steps {
                bat 'docker run -d -p 8081:8080 --name python-web-container python-webapp'
            }
        }
    }
}
